name:                haskell-cftt
version:             0.1.0.0
# license:             MIT
# author:
# maintainer:
# copyright:

ghc-options:
  - -Wall
  - -Wno-missing-signatures
  - -Wno-name-shadowing
  - -Wno-unused-do-bind
  - -Wno-unused-matches
  - -Wno-partial-type-signatures

default-extensions:
  - AllowAmbiguousTypes
  - BlockArguments
  - DataKinds
  - DeriveFunctor
  - EmptyCase
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneKindSignatures
  - Strict
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UnicodeSyntax
  - ViewPatterns

library:
  source-dirs: .
  dependencies:
    - base >= 4.7 && < 5
    - mtl
    - transformers
    - template-haskell
