
name:        staged-fp
version:     0.1.0.0
license:     MIT
category:    Language
description: "Experimental compiler with staging"
author:      "Andr치s Kov치cs"
maintainer:  "puttamalac@gmail.com"
copyright:   "2021 Andr치s Kov치cs"

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DerivingVia
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - KindSignatures
  - LambdaCase
  - MagicHash
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - UnboxedTuples
  - ViewPatterns
  - MultiParamTypeClasses
  - FunctionalDependencies

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-unused-binds
  - -Wno-unused-matches
  - -Wno-missing-signatures
  - -Wno-unused-do-bind
  - -Wno-unticked-promoted-constructors
  - -fplugin-opt=Test.Inspection.Plugin:skip-O0
  - -O
  - -fmax-worker-args=12
  # - -ddump-simpl
  # - -ddump-to-file
  # - -dsuppress-all
  # - -dno-suppress-type-signatures
  # - -ddump-stg


library:
  source-dirs:
    - src
  dependencies:
    - bytestring
    - containers
    - primdata
    - dynamic-array
    - flatparse
    - hashable
    - inspection-testing
    - template-haskell
    - unordered-containers
    - microlens
    - microlens-th

executables:
  app:
    source-dirs:
      - app
    main:
      Main.hs
    ghc-options:
      # - -fllvm
      # - -O2
      - -rtsopts
    dependencies:
      - staged-fp
      - dynamic-array
      - bytestring
