resolver: lts-16.31

packages:
- .

ghc-options:
  "$everything": -split-sections

extra-deps:
# - flatparse-0.2.0.0

- git: https://github.com/AndrasKovacs/flatparse.git
  commit: 21caeaf38a1ae1aef9d4397815c71ea214e49db8

# - /home/kutta/home/Dropbox/src/flatparse/

- git: https://github.com/AndrasKovacs/dynamic-array.git
  commit: 04fc3d5c99b8a4fed7f45c04ea047b57dede3aa5
- git: https://github.com/AndrasKovacs/primdata.git
  commit: d050c16a088e973de879941aafb2c07c319a7a31
- inspection-testing-0.4.3.0
