name:                haskell-cftt
version:             0.1.0.0
# license:             MIT
# author:
# maintainer:
# copyright:

flags:
  dump:
    description: dump core, stg and cmm to files
    default: false
    manual: true

ghc-options:
  - -Wall
  - -Wno-missing-signatures
  - -Wno-name-shadowing
  - -Wno-unused-do-bind
  - -Wno-unused-matches
  - -Wno-partial-type-signatures
  - -O0

when:
  - condition: flag(dump)
    ghc-options:
      - -ddump-simpl
      # - -ddump-stg-final
      # - -ddump-cmm
      - -dsuppress-all
      - -dno-suppress-type-signatures
      - -ddump-to-file

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - DataKinds
  - DeriveFunctor
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneKindSignatures
  - Strict
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UnicodeSyntax
  - ViewPatterns

library:
  source-dirs: .
  dependencies:
    - base >= 4.7 && < 5
    - mtl
    - transformers
    - template-haskell
