
name:                rtcg
version:             0.1.0.0
# github:              "AndrasKovacs/elaboration-zoo"
license:             BSD3
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2024 Andr치s Kov치cs"
category:            Language

description:         "Dependently typed language supporting runtime code generation"

default-extensions:
- BangPatterns
- BlockArguments
- ConstraintKinds
- DeriveAnyClass
- DerivingVia
- EmptyCase
- EmptyDataDeriving
- FunctionalDependencies
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- ImplicitParams
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- Strict
- TemplateHaskell
- TupleSections
- ViewPatterns

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- microlens-platform
- mtl

source-dirs: .

executable:
  main: Main.hs
  ghc-options:
  - -O
