
name:        2ltt
version:     0.1.0.0
license:     MIT
author:      "Andr치s Kov치cs"
maintainer:  "puttamalac@gmail.com"
copyright:   "2022 Andr치s Kov치cs"
category:    Language
description: "Small implementation of a two-level type theory, for demonstrating staged compilation"
bug-reports: https://github.com/AndrasKovacs/staged/issues
github:      AndrasKovacs/staged

default-extensions:
- BangPatterns
- BlockArguments
- ConstraintKinds
- DeriveAnyClass
- DerivingVia
- FlexibleContexts
- LambdaCase
- PatternSynonyms
- StandaloneKindSignatures
- Strict
- TupleSections
- ViewPatterns

executable:
  source-dirs: .
  main: Main.hs
  dependencies:
  - base >= 4.7 && < 5
  - containers
  - megaparsec
  ghc-options:
  - -O
  - -rtsopts
  - -with-rtsopts= "-A64M"
  - -Wall
  - -Wno-name-shadowing
  - -Wno-missing-signatures
  - -Wno-unused-do-bind
  - -Wno-unused-matches
